### ISSUE TITLE
meta-data tag not parsed correctly in AndroidManifest.xml

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#1399]
There are several issues all pointing to the same underlying problem, so I'm going to consolidate them here. #1397, #1025, #1071.

**Comment by gpeal** [comment]
I am still seeing this with the latest 3.0-SNAPSHOT and haven't been able to get any of the workaround to work.

**Comment by erd** [comment]
How are you running your test? Does the meta-data tag use a resource reference (i.e. is it the google play services version)?

**Comment by gpeal** [comment]
I am referencing it directly with @integer/google_play_services_version. I tried making a reference to it with something like `<integer android:name="google_play_services_version_alias">@integer/google_play_services_version</integer` but that complained about the value already being defined or something along those lines.

**Comment by martintama** [comment]
@gpeal add  tools:replace="android:value" as AS suggests to the metadata tag. Worked for me. Should be something like this:

```xml
<meta-data android:name="com.google.android.gms.version" tools:replace="android:value"
            android:value="@integer/gms_version" />
```
and "@integer/gms_version" being defined in a custom value file like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer name="gms_version">@integer/google_play_services_version</integer>
</resources>
```
As it was sugested in #1025.

**Comment by AdamMTGreenberg** [comment]
I am getting the message:
>>java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 6587000 but found 0.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

with the above solution.  On org.robolectric:robolectric:2.4 and com.android.tools.build:gradle:1.1.2 and com.google.android.gms:play-services:6.5.87

**Comment by chrisjenx** [comment]
I actually went for this in the end. the tools:replace didn't do anything really:

```xml
<meta-data
            android:name="com.google.android.gms.version"
            tools:node="replace"
            android:value="6587000"/>
```

**Comment by jongerrish** [comment]
The Google Play Services version is a private implementation detail of the
gcore library you are using. You don't want it in your manifest, rather let
the build system merge it into your binary. Are you using gradle?

**Comment by chrisjenx** [comment]
If I let it merge it in then our tests fail using the built in unit test.
It can't read the meta tag. The above works.

**Comment by jongerrish** [comment]
I think there are two things:-

1) The meta-data tag is a private implementation detail of the google play
services library - you shouldn't need to add it to your manifest, the build
tools should do that for you.

2) You should probably be mocking out the Google Play Services library
anyway, or maybe Robolectric will shadow it for you, if you're on 3.0
snapshot there is a ShadowGooglePlayServices class.

Are you using 3.0 snapshot?

What is your stacktrace if you remove it?

**Comment by simtse** [comment]
I tried putting in the hack from @chrisjenx to hard code the value into the manifest to get passed this problem of the resources not loading. Even with DeckardGradle where I added the following, I still get the problem of the NullPointerException trying to load the meta data from the Android Manifest.


Added the following to DeckardGradle and failed to run.
```
    compile 'com.google.android.gms:play-services-maps:6.5.+'
    compile 'com.google.android.gms:play-services-base:6.5.+'
```


@jongerrish , you have been super helpful this last 48 hours. Anyway, I don't know how the ShadowGooglePlayServices class helps with the resource handling in this case. I am using the following gradle dependencies for my robolectric gradle setup.

```
    androidTestCompile 'org.robolectric:android-all:+'
    androidTestCompile 'org.robolectric:shadows-multidex:3.0-SNAPSHOT'
    androidTestCompile 'org.robolectric:shadows-play-services:3.0-SNAPSHOT'
    androidTestCompile('org.robolectric:robolectric:3.0-SNAPSHOT') {
        exclude module: 'classworlds'
        exclude module: 'commons-logging'
        exclude module: 'httpclient'
        exclude module: 'maven-artifact'
        exclude module: 'maven-artifact-manager'
        exclude module: 'maven-error-diagnostics'
        exclude module: 'maven-model'
        exclude module: 'maven-project'
        exclude module: 'maven-settings'
        exclude module: 'plexus-container-default'
        exclude module: 'plexus-interpolation'
        exclude module: 'plexus-utils'
        exclude module: 'wagon-file'
        exclude module: 'wagon-http-lightweight'
        exclude module: 'wagon-provider-api'
    }
```

This is my robolectric test runner as well so we can see if my setup is ok.
```
	@Override
	protected AndroidManifest getAppManifest(Config config) {
		String manifestProperty = "../app/src/main/AndroidManifest.xml";
		String resProperty = "../app/src/main/res";
		String assetesProperty = "../app/src/main/assets";
		return new AndroidManifest(Fs.fileFromPath(manifestProperty),
				Fs.fileFromPath(resProperty),
				Fs.fileFromPath(assetesProperty)) {
			@Override
			public int getTargetSdkVersion() {
				return MAX_SDK_SUPPORTED_BY_ROBOLECTRIC;
			}
		};
```


As for the stack trace on the 3.0 snap shot, this is what I get if I don't have @chrisjenx  hack solution

```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:226)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.robolectric.AndroidManifest$MetaData.init(AndroidManifest.java:736)
	at org.robolectric.AndroidManifest.initMetaData(AndroidManifest.java:395)
	at org.robolectric.res.builder.RobolectricPackageManager.addManifest(RobolectricPackageManager.java:366)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:68)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	... 35 more
```

**Comment by jongerrish** [comment]
You sure you are running the latest snapshot? The line numbers don't seem
to match up:-

https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/manifest/AndroidManifest.java

Unfortunately I'm not familiar with gradle and the plugins, we use an in
house build system, but the way the build systems _should_ work is that:-

* You shouldn't need to add that Google Play Services meta-data tag to your
manifest (it is a private implementation detail of the play services
library that you depend upon, it is there to make sure that the play
services apk is at least the min version required by the version of the
play services client library you have linked your code against). If you
open up the play services aar then you will find this meta-data tag in its
manifest, and you will also see the definition of
@integer/google_play_services_version in the res directory of that exploded
aar file.

* Gradle or what ever build system you use should be merging the manifest
entries and resources of your app, plus any libraries in the transitive
closure for you into a single merged and complete versions for your app
binary (this is why your app works if you deploy to a phone).

* Robolectric gradle plugin _should_ be doing the same thing for you for
your unit tests. That is to say, you should not need to declare the
meta-data tag for google play services, but the plugin should be generating
the manifest and merged resources that include these IF you have a
dependency on them, but we don't use these so I can't comment.

Looking at your custom test runner I see that you are hard coding your
manifest and res paths, I suspect this is causing Robolectric to find your
apps manifest and resources, but really you want to be using the merged
manifest and resources that your build system provides you.

FWIW I recommend not having a custom test runner subclass for these reasons.

**Comment by azri92** [comment]
@jongerrish I followed your advice that "You shouldn't need to add that Google Play Services meta-data tag to your manifest" and apparently it works! I guess it's enough that you have the dependency in Gradle?

Now I'm getting a NoSuchMethodError. Oh Robolectric..

**Comment by jongerrish** [comment]
Stack trace? Api version?

**Comment by azri92** [comment]
It's ok. I dropped Robolectric and went around just using ActivityInstrumentationTestCase2. Thanks!

**Comment by guilty787** [comment]
I solved this issue by adding a reference to the google play services lib in my project.properties file.

The file now looks like this:

android.library.reference.1=build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3
android.library.reference.2=build/intermediates/exploded-aar/com.android.support/support-v4/21.0.3
android.library.reference.3=build/intermediates/exploded-aar/com.google.android.gms/play-services/6.5.87

Using Robolectric 3.0-SNAPSHOT.

The issue here is that the value is referencing a resource field inside the google play services lib, and so Robolectric couldn't find it unless referenced in the project.properties.

If you don't already have a project.properties file in your project, you need to make sure to add it to the root project (sibling of your app folder), and make sure your AndroidManifest object correctly loads it. I had an issue with this, that my AndroidManifest file wasn't calculating the baseDir properly, so I subclassed it and overrid the getBaseDir() function which is used when loading the libraries.

Hope this helps!

**Comment by jaredsburrows** [comment]
Has anyone upgraded to RC3? I have plenty of meta tags in my `AndroidManifest.xml` and I have never bene able to reproduce this.

**Comment by jaredsburrows** [comment]
@erd  This is similar to this issue: https://github.com/robolectric/robolectric/issues/1329.

I have never seen this problem, I have plenty of apps that use both `metadata` without any problem with Robolectric.

**Comment by pdegand** [comment]
Hi, using RC3 here and still having the problem

In my AndroidManifest, i have this meta data : 

    <meta-data
            android:name="com.google.android.wearable.beta.app"
            android:resource="@xml/wearable_desc" />

When Robolectric is converting the metadata into a Bundle, the entry value for the key "com.google.android.wearable.beta.app" is null then crashing with NPE line 701 of DefaultPackageManager.

    java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:238)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    Caused by: java.lang.NullPointerException
	at org.robolectric.res.builder.DefaultPackageManager.metaDataToBundle(DefaultPackageManager.java:701)
	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:479)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:74)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:421)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
	... 13 more

**Comment by jaredsburrows** [comment]
@pdegand Wha if you specified an `AndroidManifest.xml` without that `meta-tag`?

**Comment by pdegand** [comment]
@jaredsburrows  If I remove this `meta-tag`, the problem disappear. I actually noticed that I reproduce this bug with a `meta-tag` referencing a `resource`. All the meta with a `value` are properly handled by Robolectric.

This works :

    <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

This crashes (same stack trace as above) : 

    <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:resource="@string/facebook_app_id" />

**Comment by jaredsburrows** [comment]
If you know of a configuration that works, then setup it up in your test. Do not wait for the Robolectric fix.

Here is how your project should look like:

    |-- src
        |-- main
            |-- AndroidManifest.xml  <-- your manifest
        |-- test
            |-- AndroidManifest.xml  <-- test manifest

**Comment by pdegand** [comment]
I'v found a workaround (i put this meta only in my release Manifest). But i thought it might be good for the Robolectric team that there might be a bug somewhere.

Thanks

**Comment by jaredsburrows** [comment]
@pdegand That sounds good! @erd  What do you think? Can we close or continue trying add meta-data support.

**Comment by erd** [comment]
Robolectric doesn't handle dereferencing string resources when parsing the manifest, so yes, this is still a defect.

**Comment by pdegand** [comment]
fyi, my bug was actually that a flavor was overriding the default applicationId, therefor, Robolectric was not able to load my R.class, because it is loaded with the current applicationId. To fix this, override packageName in @Config or in robolectric.properties.

**Comment by RyanNewsom** [comment]
This has been open for almost 2 years, what gives? I am currently having this issue in a project I'm working on. Sometimes the tests run fine, other times I get this error and they fail. We are considering dropping Roboelectric because of this.

**Comment by jaredsburrows** [comment]
@erd @RyanNewsom Issues would be fixed faster and people would contribute more if they released Robolectric more often. I has almost been a year since Robolectric 3.0 has been released: https://github.com/robolectric/robolectric/releases.

**Comment by RyanNewsom** [comment]
What's really weird, is if I comment out that meta tag, they still pass. Yet intermittently when it's there, some of the tests fail with this "missing meta tag" complaint.

**Comment by jaredsburrows** [comment]
Can you post your manifest?

**Comment by RyanNewsom** [comment]
Not the entire thing it's proprietary.. Here's a snapshot.

<application
            <meta-data
            android:name="com.google.android.gms.version" tools:replace="android:value"
            android:value="@integer/google_play_services_version" />

**Comment by erd** [comment]
@RyanNewsom If Robolectric does not meet your needs from a testing standpoint, I would absolutely suggest that you switch to something else.

**Comment by RyanNewsom** [comment]
It meets our needs and I love the framework, but I don't love having tests intermittently fail with this error. It is really messing up our continuous integration, I'm also clearly not the only one with this problem.

**Comment by jongerrish** [comment]
@RyanNewsom what continuous build system are you using?

You shouldn't need to add in the meta-data tag for "com.google.android.gms.version" since this is defined in the Google Play Services client library AndroidManifest.xml and should be merged by the build system automatically into your apps manifest if you have a dependency on it.

I don't use Gradle, but I believe it would also be merged in for tests also.

I believe I fixed some issue with meta-data parsing, do you want to give running against the latest snapshot a try and then post back with your findings?

**Comment by RyanNewsom** [comment]
Yes absolutely @jongerrish I'll post up Tuesday! :+1:

**Comment by RyanNewsom** [comment]
So... update. 

3.0-SNAPSHOT:
Note: I tried using 3.1-SNAPSHOT but I'm getting a failed to resolve error, so I'm using 3.0-SNAPSHOT.

running all the tests, 5 times they all pass, then the 6th time, 17/78 tests failed with this error & another error. 
`java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  
You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`

What's weird, some of the other tests that failed have this error.
`android.view.InflateException: XML file build/intermediates/res/merged/develop/unitTest/layout/activity_summary.xml line #-1 (sorry, not yet implemented): Error inflating class fragment
`

Maybe there is a correlation between the two errors?

I ran it a 7th time, again 17/78 tests failed with these errors.
8th time, all tests pass.
9th time, all tests pass.
10th time, all tests pass.

It's so weird how this is intermittent...

**Comment by Gauravwdh** [comment]
Got similar issue:

java.lang.NullPointerException
	at org.robolectric.manifest.MetaData.init(MetaData.java:55)
	at org.robolectric.manifest.AndroidManifest.initMetaData(AndroidManifest.java:377)

Robolectric (robolectric 3.1) can parse @string resource or direct value for meta-data in AndroidManifest.xml. But it is unable to parse @drawable resource in AndroidManifest. So commented those meta-data for a while for testing.

**Comment by barriosnahuel** [comment]
Hi! I'm facing this problem too, but as others mention before it is random! =(

I'm using Robolectric 3.0... 3.1 is released but this issue is still open.. am I wrong if I think that 3.1 still has this error? Does anyone tried with 3.1?

**Comment by jhansche** [comment]
Trying to run tests with Android Gradle Plugin 3.0.0-beta2, and still running into this error.

So far I've traced the issue back to `org.robolectric.res.ResourceTableFactory.parseResourceFiles()`, where running from command-line gradlew works fine and logs:

```
DEBUG: Loading resources for com.example.app from <projectDir>/build/intermediates/merged-not-compiled-resources/debug...
```

But running from Android Studio fails and logs:
```
DEBUG: Loading resources for com.example.app from build/intermediates/res/merged/debug...
```

The resource (`facebook_app_id` and `google_play_services_version` are the examples mentioned in these issues) exists only in the first path, while there's nothing at the latter path.

Digging deeper, I see there's a difference between running from the command-line (uses `org.robolectric.internal.DefaultManifestFactory.create()`) and running from Android Studio (uses `org.robolectric.internal.GradleManifestFactory.create()`).  The problem seems to be that DefaultManifestFactory is picking up the resource location using the `android_merged_resources` property; while GradleManifestFactory is looking in a series of predetermined paths, until it finds one that exists, and then runs with that.

So because the `build/intermediates/res/merged/debug` path *does* exist, that one is selected -- but with the latest plugin, that path is actually _empty_ (does not contain a `values/values.xml` file).  Running from gradlew works because the property is set to the correct/expected path of `build/intermediates/merged-not-compiled-resources/debug`, which _does_ contain the values/values.xml file.

That's as far as I've gotten so far today. I'll look more tomorrow.

**Comment by jhansche** [comment]
I made a commit (see link here ^) that attempts to fix this by adding the `merged-not-compiled-resources` path to the list of paths that are auto-detected by GradleManifestFactory.

But I don't know enough about how AGP and AAPT2 are choosing that to know if this is an appropriate fix or not.  It does fix my issue of all tests failing from AS -- they now pass in AS and still pass in command-line gradle.  I'm happy to open the pull request, but I'm not 100% confident that this is the correct fix.

**Comment by jongerrish** [comment]
We should be using DefaultManifestFactory in both cases, but there is a bug
in AS where the relevant properties file is not added to the class path
which needs to happen for that to work. There is a bug but I'm not at my
computer right now.

The GradleManifestFactory is the old ad-hoc integration which as you say
looks at a bunch of different paths where AGP placed the merged directory
across various versions.

The AS bug should be fixed in the next version of AS I believe and the
DefaultManifestFactory implementation will be a stable integration going
forward. We'll remove GradleManifestFactory at some point as that will
cease to work probably sometime in Q3/4 when AS stops producing merged raw
XML resource directories.

**Comment by ber4444** [comment]
Still having this problem with robolectric 3.6.1, any update on the @jhansche fix? Why is it still not merged?

**Comment by shalzz** [comment]
Hi!
Adding https://github.com/robolectric/robolectric/issues/3826#issuecomment-378436551 with 3.8, fixed the issue for me.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

**Comment by xlstefan** [comment]
Still not resolved.
Using roboelectric 4.3, gradle 3.4.1

Getting this error:
`java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist. You must have the following declaration within the <application> element: <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
`

In manifest I have added this:
`        <meta-data
            android:name="com.google.android.gms.version"
            tools:replace="android:value"
            android:value="@integer/gms_version" />`

I tried solution from here (bellow the comment) but it didn't help.

==================================
Just had the same problem and worked around it by simply adding a local integers.xml file:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer name="gms_version">@integer/google_play_services_version</integer>
</resources>
```

I referenced the `@integer/gms_version` in my manifest instead and it seems to work. Still would be ideal to fix this issue though

_Originally posted by @DanielGrech in https://github.com/robolectric/robolectric/issues/1025#issuecomment-42730563_ 

==================================

Can someone help please?

**Comment by xMickeymikex** [comment]
@xlstefan I'm struggling with this issue as well. Any solutions?

**Comment by jongerrish** [comment]
You don't need to add this explicitly to your manifest, it is included in
the play services client manifest and the merged into the final manifest by
the build tools manifest merger.

You just need a dependency on play services from what ever module code is
calling the play services Java code that is making that check.

**Comment by jamessolo12** [comment]
@jongerrish @erd can we re-open this issue, I'm still seeing it in 4.3 and I'm not the only one.
