### ISSUE TITLE
android.view.InflateException: XML file build\intermediates\res\merged\debug\layout\abc_screen_simple.xml line #-1 (sorry, not yet implemented): XML file build\intermediates\res\merged\debug\layout\abc_screen_simple.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v7.widget.FitWindowsLinearLayout

### ISSUE THREAD

**Issue by YanYanLun** [robolectric/robolectric#2585]
### Robolectric 3.1.1 & Android Version sdk 23
android.view.InflateException: XML file build\intermediates\res\merged\debug\layout\abc_screen_simple.xml line #-1 (sorry, not yet implemented): XML file build\intermediates\res\merged\debug\layout\abc_screen_simple.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v7.widget.FitWindowsLinearLayout

	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:413)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
	at com.sparxo.checkin.activity.LoginActivity.onCreate(LoginActivity.java:53)
	at android.app.Activity.performCreate(Activity.java:6237)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:340)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:96)
	at com.sparxo.checkin.LoginActivityTest.testView(LoginActivityTest.java:22)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:465)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: android.view.InflateException: XML file build\intermediates\res\merged\debug\layout\abc_screen_simple.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v7.widget.FitWindowsLinearLayout
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	... 37 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$createSubDecor(AppCompatDelegateImplV7.java:413)
	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$ensureSubDecor(AppCompatDelegateImplV7.java:309)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$setContentView(AppCompatDelegateImplV7.java:273)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatActivity.$$robo$$setContentView(AppCompatActivity.java:136)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
	at com.sparxo.checkin.activity.LoginActivity.onCreate(LoginActivity.java:53)
	at android.app.Activity.$$robo$$performCreate(Activity.java:6237)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:340)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:96)
	at com.sparxo.checkin.LoginActivityTest.testView(LoginActivityTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:465)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: javax/microedition/khronos/opengles/GL
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:224)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:54)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:114)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:18)
	at android.graphics.Canvas.<clinit>(Canvas.java)
	at android.view.View.__constructor__(View.java:3804)
	at android.view.View.<init>(View.java)
	at android.view.ViewGroup.<init>(ViewGroup.java)
	at android.widget.LinearLayout.<init>(LinearLayout.java)
	at android.support.v7.widget.FitWindowsLinearLayout.<init>(FitWindowsLinearLayout.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:413)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
	at com.sparxo.checkin.activity.LoginActivity.onCreate(LoginActivity.java:53)
	at android.app.Activity.performCreate(Activity.java:6237)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:340)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:96)
	at com.sparxo.checkin.LoginActivityTest.testView(LoginActivityTest.java:22)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:465)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javax.microedition.khronos.opengles.GL
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:124)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:224)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:54)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:114)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:18)
	at android.graphics.Canvas.<clinit>(Canvas.java)
	at android.view.View.$$robo$$__constructor__(View.java:3804)
	at android.view.View.<init>(View.java)
	at android.view.View.<init>(View.java)
	at android.view.ViewGroup.<init>(ViewGroup.java)
	at android.widget.LinearLayout.<init>(LinearLayout.java)
	at android.widget.LinearLayout.<init>(LinearLayout.java)
	at android.widget.LinearLayout.<init>(LinearLayout.java)
	at android.support.v7.widget.FitWindowsLinearLayout.<init>(FitWindowsLinearLayout.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$createSubDecor(AppCompatDelegateImplV7.java:413)
	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$ensureSubDecor(AppCompatDelegateImplV7.java:309)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$setContentView(AppCompatDelegateImplV7.java:273)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatActivity.$$robo$$setContentView(AppCompatActivity.java:136)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
	at com.sparxo.checkin.activity.LoginActivity.onCreate(LoginActivity.java:53)
	at android.app.Activity.$$robo$$performCreate(Activity.java:6237)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:340)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:96)
	at com.sparxo.checkin.LoginActivityTest.testView(LoginActivityTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:465)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more

Process finished with exit code -1

@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 23)
public class LoginActivityTest {
    @Test
    public void testView() {
        LoginActivity activity = Robolectric.setupActivity(LoginActivity.class);
        Assert.assertNotNull(activity);
//
//        EditText email = (EditText) activity.findViewById(R.id.email);
//        Assert.assertNotNull(email);
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.zplesac:connectionbuddy:+'
    compile 'com.daimajia.androidanimations:library:1.1.3@aar'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.easing:library:1.0.1@aar'
    compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.google.code.gson:gson:2.2.+'
    compile 'com.androidadvance:topsnackbar:0.0.9'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile 'com.daimajia.swipelayout:library:1.2.0@aar'
    compile 'com.tencent.bugly:crashreport:2.1.3'

    // Unit test
    testCompile 'junit:junit:4.12'
    testCompile('org.robolectric:robolectric:3.1.1') {
        exclude module: 'support-v4'
        exclude module: 'qrcodereaderview'
        exclude module: 'topsnackbar'
    }

**Comment by YanYanLun** [comment]
Problem has been solved，compile 'com.android.support:appcompat-v7:23.3.0' and compile 'com.android.support:design:23.3.0' Other packages have been introduced，so，delete it

**Comment by rahul-narkhede** [comment]
@YanYanLun  Can you elaborate on how you solved this problem?  Any help would be appreciated.

**Comment by rahul-narkhede** [comment]
@DAlexIV  You need to add (android-all.jar)[http://search.maven.org/#artifactdetails%7Corg.robolectric%7Candroid-all%7C7.0.0_r1-robolectric-0%7Cjar] dependency for test.

**Comment by ddmytrenko** [comment]
@rahul-narkhede Still have the same issue :( android-all dep did not help (and I cannot see how it can possibly help )

**Comment by liangjh08** [comment]
I solved a similar problem by romoveing the "imeActionId" attribute in the EditText element.
