### ISSUE TITLE
Problem of testing apps with data-binding in module(s)

### ISSUE THREAD

**Issue by XinyueZ** [robolectric/robolectric#3789]
Tests couldn't go on if the App is based on multi-modules.

A normal app
 - base-app(baseFeature)
 - some other modules
 - install (apk)
 - instant (instant app)

I have added all these in ```gradle.properties```, however, the tests cannot go on, they throw 
`
java.lang.NoClassDefFoundError: android/databinding/DataBinderMapperImpl`

```
android.enableD8.desugaring=true
android.databinding.enableV2=true
android.enableExperimentalFeatureDatabinding=true
```

I am sure that all works before I switched to multi-modules.

Version of robolectric: 3.7.1

[stackoverflow](https://stackoverflow.com/questions/48949628/tests-down-if-run-with-robolectric-for-apps-with-data-binding-in-module)

**Comment by emartynov** [comment]
I got similar exceptions while updated AGP to 3.1.0-beta4 (which comes with new DataBinding version).

Stack trace:
```
android.view.InflateException: XML file /Users/eugenmartynov/Development/source/android/app/build/intermediates/merged-not-compiled-resources/debug/layout/activity_bank_suggestions.xml line #-1 (sorry, not yet implemented): XML file /Users/eugenmartynov/Development/source/app/build/intermediates/merged-not-compiled-resources/debug/layout/bank_suggestions_list.xml line #-1 (sorry, not yet implemented): Error inflating class app.tools.views.state.StateView

Caused by: android.view.InflateException: XML file /Users/eugenmartynov/Development/source/app/build/intermediates/merged-not-compiled-resources/debug/layout/bank_suggestions_list.xml line #-1 (sorry, not yet implemented): Error inflating class app.tools.views.state.StateView
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$parseInclude(LayoutInflater.java:995)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.android.internal.policy.PhoneWindow.$$robo$$setContentView(PhoneWindow.java:419)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java)
	at android.app.Activity.$$robo$$setContentView(Activity.java:2683)
	at android.app.Activity.setContentView(Activity.java)
	at android.databinding.DataBindingUtil.$$robo$$setContentView(DataBindingUtil.java:303)
	at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at android.databinding.DataBindingUtil.$$robo$$setContentView(DataBindingUtil.java:284)
	at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at app.customercare.banksuggestions.ui.BankSuggestionsNavigation.onActivityAttached(BankSuggestionsNavigation.kt:25)
	at appl.extensions.BaseNavigation.attachActivity(BaseNavigation.java:40)
	at app.customercare.banksuggestions.ui.BankSuggestionsNavigationShould.setUp(BankSuggestionsNavigationShould.kt:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NoClassDefFoundError: android/arch/lifecycle/LiveData
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:278)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:56)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:150)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:20)
	at android.databinding.ViewDataBinding.<clinit>(ViewDataBinding.java)
	at android.databinding.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:664)
	at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
	at android.databinding.DataBindingUtil.bindToAddedViews(DataBindingUtil.java:327)
	at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:128)
	at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
	at app.tools.views.state.StateView.<init>(StateView.java:84)
	at app.views.state.StateView.<init>(StateView.java:70)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
	at android.app.Activity.setContentView(Activity.java:2683)
	at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
	at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
	at app.customercare.banksuggestions.ui.BankSuggestionsNavigation.onActivityAttached(BankSuggestionsNavigation.kt:25)
	at app.extensions.BaseNavigation.attachActivity(BaseNavigation.java:40)
	at app.customercare.banksuggestions.ui.BankSuggestionsNavigationShould.setUp(BankSuggestionsNavigationShould.kt:26)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	... 1 more
Caused by: java.lang.ClassNotFoundException: android.arch.lifecycle.LiveData
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:154)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:114)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:107)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:278)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:56)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:150)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:20)
	at android.databinding.ViewDataBinding.<clinit>(ViewDataBinding.java)
	at android.databinding.DataBinderMapperImpl.$$robo$$getDataBinder(DataBinderMapperImpl.java:664)
	at android.databinding.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java)
	at android.databinding.DataBindingUtil.$$robo$$bind(DataBindingUtil.java:199)
	at android.databinding.DataBindingUtil.bind(DataBindingUtil.java)
	at android.databinding.DataBindingUtil.$$robo$$bindToAddedViews(DataBindingUtil.java:327)
	at android.databinding.DataBindingUtil.bindToAddedViews(DataBindingUtil.java)
	at android.databinding.DataBindingUtil.$$robo$$inflate(DataBindingUtil.java:128)
	at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java)
	at android.databinding.DataBindingUtil.$$robo$$inflate(DataBindingUtil.java:95)
	at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java)
	at app.tools.views.state.StateView.<init>(StateView.java:84)
	at app.tools.views.state.StateView.<init>(StateView.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$parseInclude(LayoutInflater.java:995)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.android.internal.policy.PhoneWindow.$$robo$$setContentView(PhoneWindow.java:419)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java)
	at android.app.Activity.$$robo$$setContentView(Activity.java:2683)
	at android.app.Activity.setContentView(Activity.java)
	at android.databinding.DataBindingUtil.$$robo$$setContentView(DataBindingUtil.java:303)
	at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at android.databinding.DataBindingUtil.$$robo$$setContentView(DataBindingUtil.java:284)
	at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at app.customercare.banksuggestions.ui.BankSuggestionsNavigation.onActivityAttached(BankSuggestionsNavigation.kt:25)
	at app.extensions.BaseNavigation.attachActivity(BaseNavigation.java:40)
	at app.customercare.banksuggestions.ui.BankSuggestionsNavigationShould.setUp(BankSuggestionsNavigationShould.kt:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more
```

**Comment by emartynov** [comment]
Similar happens when I run from console

**Comment by emartynov** [comment]
The quick workaround is:

```  testImplementation 'android.arch.lifecycle:livedata:1.1.0'```

**Comment by XinyueZ** [comment]
Doesn't work for me

**Comment by AamirAbro** [comment]
facing the same issue :(

**Comment by AamirAbro** [comment]
this works https://github.com/robolectric/robolectric/issues/3789#issuecomment-370467113
thanks @emartynov

**Comment by jongerrish** [comment]
Mind filing a bug against Android studio / Gradle?

**Comment by JorgeMucientes** [comment]
it worked for me as well thanks @emartynov

**Comment by smpete** [comment]
I have the same problem on Robolectric `3.8` and Gradle `3.1.0`. I can't seem to get an binding to inflate with either the application context or an activity context. The V2 data binding compiler has no effect.

Here's the stacktrace:
```
java.lang.NoClassDefFoundError: android/databinding/DataBinderMapperImpl

	at com.example.databinding.ItemBinding.inflate(ItemBinding.java:84)
	at com.example.ItemTest.testSingleClick(ItemTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:573)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:261)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassNotFoundException: android.databinding.DataBinderMapperImpl
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:154)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:114)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:107)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
```

**Comment by rus1f1kat0r** [comment]
@smpete have you found any workaround? I have the same issue and really struggling to fix it

**Comment by jongerrish** [comment]
If you can possibly use AS 3.3 and Robolectric 4.0 you'll get seamless
integration with binary resource support which means no configuration, more
fidelity, less memory overhead and faster test execution.

Otherwise AS 3.2 and Robolectric 3.8 (maybe since 3.6 possibly) there is
seamless integration with raw, merged resources.

Check out the getting started guide for details.

If you're really stuck on an older version, put a breakpoint in
GradleManifestFactory see what value you're getting for the resource
directory and try and match this with where is actually is. The reason is
the integration used to be a hack searching for the merged resources
directory and in your case it's not finding it.

**Comment by rus1f1kat0r** [comment]
@jongerrish thanks for the help. Unfortunately updating to AS 3.2 beta1 and Robolectric 3.8 doesn't solve my issue. 
I am still getting `java.lang.ClassNotFoundException: android.databinding.DataBinderMapperImpl`. I have started to dig into implementation details and it seems like I have `DataBinderMapperImpl` class to be generated for my library module which exists under `generated` folder, but it exists in wrong package. The `DataBindingUtil` class creates static reference to `DataBinderMapperImpl` and assumes it exists in the `android.databinding` package.

```
public class DataBindingUtil {
    private static DataBinderMapper sMapper = new DataBinderMapperImpl();
```
If I include my library in application, the application also generates another `DataBinderMapperImpl` class and puts it in desired `android.databinding` package. In my case it looks like that

```
package android.databinding;

public class DataBinderMapperImpl extends MergedDataBinderMapper {
  DataBinderMapperImpl() {
    addMapper(new my.library.package.name.DataBinderMapperImpl());
  }
}
```
I assume that this part is missing when I try to run my unit tests for the library which causes `ClassNotFoundException`.
Any ideas about how could I make it working would be much appreciated.

**Comment by bolein** [comment]
@smpete @rus1f1kat0r were you able to solve this?

**Comment by rus1f1kat0r** [comment]
@bolein I haven't found the proper solution so far. However I managed to make it working.
For your library test directory you can put the missing class. In my case it looks like 

```java 
package android.databinding;

public class DataBinderMapperImpl extends MergedDataBinderMapper {
  DataBinderMapperImpl() {
    addMapper(new my.library.package.name.DataBinderMapperImpl());
  }
}
```
This hack works for library tests and doesn't pollute the bundle as it only exists for test variant. 
Hope it'll help you.

**Comment by jongerrish** [comment]
Have you tried the binary resource support? There's a much higher chance of
resources just working with that mode.

**Comment by rus1f1kat0r** [comment]
@jongerrish I did actually and it didn't help to solve the problem. May be I misunderstood the root issue, but what I see doesn't seem to be a resource issue. Please correct me if I am wrong. Could missing generated class be fixed with a binary resource mode?

**Comment by bolein** [comment]
@rus1f1kat0r your hack doesn't work for me. I didn't have my `ViewDataBinding` classes generated for some reason. So I solved this by also implementing a `FakeViewDataBinding`.

```Kotlin
package android.databinding

import android.view.View

class DataBinderMapperImpl : MergedDataBinderMapper() {

  override fun getDataBinder(
    bindingComponent: DataBindingComponent?,
    view: View?,
    layoutId: Int
  ): ViewDataBinding = FakeViewDataBinding(bindingComponent, view, 0)
}

class FakeViewDataBinding(
  component: DataBindingComponent?,
  view: View?,
  localFieldCount: Int
) : ViewDataBinding(component, view, localFieldCount) {

  override fun executeBindings() {
    TODO("not implemented")
  }

  override fun onFieldChange(
    localFieldId: Int,
    `object`: Any?,
    fieldId: Int
  ): Boolean {
    TODO("not implemented")
  }

  override fun invalidateAll() {
    TODO("not implemented")
  }

  override fun hasPendingBindings() = false

  override fun setVariable(variableId: Int, value: Any?) = false

}
```

However, I still don't understand why my Data Binding classes are not generated properly. Could it be a Data Binding issue?

**Comment by jongerrish** [comment]
I'm guessing the databinding class is not generated for unit tests in Android Studio, mind filing a bug against studio?

https://issuetracker.google.com/issues/new?component=192708&template=840533

**Comment by carlonzo** [comment]
this has been fixed in AGP 3.6.0-alpha7
https://issuetracker.google.com/issues/126775542

**Comment by azizbekian** [comment]
The issue is still valid up to these days.

**Comment by kingargyle** [comment]
The following worked for me using AGP 4.2.1:

    // Work around Data binding issue for tests
    kaptTest "androidx.databinding:databinding-compiler:4.2.1"

This forces kapt to run the data binding compiler for the test so the classes are available.
