### ISSUE TITLE
Fix for SandboxClassLoader broke MockK initialization.

### ISSUE THREAD

**Issue by Szauren** [robolectric/robolectric#5169]
### Description

Since 6ab25c0 MockK initialization is broken when using RobolectricTestRunner.

```
java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap
	at io.mockk.proxy.jvm.JvmMockKAgentFactory$init$Initializer.handlerMap(JvmMockKAgentFactory.kt:126)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory$init$Initializer.init(JvmMockKAgentFactory.kt:67)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:130)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
	at com.szauren.mockk.MockkInitTestCase.setUp(MockkInitTestCase.kt:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:541)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:189)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:133)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:119)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

### Steps to Reproduce

1. clone and checkout branch 
 https://github.com/Szauren/robolectric/tree/mockk-integration-tests

2. run gradle task
`./gradlew integration_tests:mockk:test`

### Robolectric & Android Version

`robolectric:4.4-SNAPSHOT`

### Link to a public git repo demonstrating the problem:
https://github.com/Szauren/robolectric/tree/mockk-integration-tests

**Comment by crgarridos** [comment]
having the same issue with the lastest version `4.4-20200213.200533-204` any plan to fix it soon ? 😬 
It seem this line are the problem https://github.com/robolectric/robolectric/commit/6ab25c087b8b6cf4e99da832745eb1df42b00ae5#diff-1ad9b99c7d64475e26235b7f984f9ac8R175-R186

**Comment by mpost** [comment]
I can also confirm the issue with robolectric 4.4-SNAPSHOT. The `JvmMockKWeakMap` is not found.

**Comment by caiquebertan** [comment]
Is anyone checking this out? I'm facing the same issue here

**Comment by caiquebertan** [comment]
for me getting back to 4.3.1 fixed the problem for now

**Comment by mpost** [comment]
I just tried out the pre-release `4.4-alpha-1` and found that `java.lang.NoClassDefFoundError: io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap` is still an issue.

**Comment by hoisie** [comment]
I will try pinging the author if 6ab25c0

**Comment by kingargyle** [comment]
@hoisie this class loader issue is probably also affecting, https://github.com/robolectric/robolectric/issues/5638

**Comment by hoisie** [comment]
One thing I noticed is that in the repro case there is an attempt to mock an Android TextView.

Just a couple notes:
1) Because the repro involves mocking an Android TextView, I could see this causing weird interactions because Robolectric's classloader instruments all Android-related classes. However, I also believe that you should be able to mock Android objects if you really want.
2) I could not repro the problem internally using the Blaze build system, which could indicate that it is a gradle/classpath issue.

**Comment by hoisie** [comment]
Created a pull request to fix this particular issue:
https://github.com/robolectric/robolectric/pull/5754

I haven't looked into the mockito issue, however. 

I've been told that Robolectric does not follow certain classloader conventions properly, so there may be a better fix available, but I don't know all the details about that yet.

**Comment by calvarez-ov** [comment]
Looks like mockk is still broken in 4.4-alpha-4.

Our test code has this:
```kotlin
fun createFoo(): com.example.Foo? {
    return mockk(relaxed = true)
}
```

And tests fail:
```
io.mockk.MockKException: Can't instantiate proxy for class com.example.Foo
        at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
        at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
        at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
        at com.mycompany.MyTest.setUp(MyTest.kt:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.mockk.proxy.MockKAgentException: Instantiation exception
        at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:54)
        at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
        ... 23 more
Caused by: java.lang.ClassCastException: Cannot cast com.example.Foo to com.example.Foo
        at java.lang.Class.cast(Class.java:3369)
        at io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:73)
        at io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
        at io.mockk.proxy.jvm.ProxyMaker.instantiate(ProxyMaker.kt:75)
        at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:42)
        ... 24 more
```

This worked with Robolectric 4.3.1.

**Comment by calvarez-ov** [comment]
Opened #5848 for the issue in the previous comment
