### ISSUE TITLE
4.3 - Annotation processors must be explicitly declared now

### ISSUE THREAD

**Issue by runningcode** [robolectric/robolectric#5245]
Reopening https://github.com/robolectric/robolectric/issues/4621 for visibility.

See this very highly rated comment:
https://github.com/robolectric/robolectric/issues/4621#issuecomment-499080171

### Description
Upgraded from Robolectric 4.2 to 4.3

```
Execution failed for task ':example-test-android:javaPreCompileInternalDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - auto-service-1.0-rc4.jar (com.google.auto.service:auto-service:1.0-rc4)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

### Workaround
Thanks @saschpe
https://github.com/robolectric/robolectric/issues/4621#issuecomment-524302709
```
implementation("org.robolectric:robolectric:4.3") {
    exclude(group = "com.google.auto.service", module = "auto-service")
}
```

Maybe due to this change? Or was this the fix?
https://github.com/robolectric/robolectric/commit/5094f9278767c818198b49fd1a91ebbf3dec0d3d

**Comment by jamesonwilliams** [comment]
Also present in `4.3.1`.

The same workaround is effective.However, I needed to use different syntax for my versions of Gradle (5.4.1) and Android Gradle Plugin (3.5.1):

```
testImplementation('org.robolectric:robolectric:4.3.1') {
    // https://github.com/robolectric/robolectric/issues/5245
    exclude group: 'com.google.auto.service', module: 'auto-service'
}
```

**Comment by Kisty** [comment]
Apparently the Android Studio bug has been fixed back in April.

@xian, can you revert this change and see if it's needed anymore? I would try it myself but last time I tried to build on Windows it didn't play ball. https://github.com/robolectric/robolectric/commit/5094f9278767c818198b49fd1a91ebbf3dec0d3d

**Comment by realdadfish** [comment]
I got the same issue with Robolectric 4.3 on AGP 3.6.0-beta04:

```
> Task :ui:javaPreCompileDebugUnitTest
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the testAnnotationProcessor configuration.
  - jetified-auto-service-1.0-rc4.jar (com.google.auto.service:auto-service:1.0-rc4)
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

If I add `.*auto-service.*` to my `android.jetifier.blacklist` configuration, I get the originally reported

```
> Task :ui:javaPreCompileDebugUnitTest
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the testAnnotationProcessor configuration.
  - auto-service-1.0-rc4.jar (com.google.auto.service:auto-service:1.0-rc4)
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

I wonder however why `auto-service` pops up as a transitive dependency at all. Shouldn't this not just be a `compileOnly` dependency as it is only relevant during compile time? Right now it seems to have `api` status (https://github.com/robolectric/robolectric/blob/master/utils/build.gradle).

**Comment by TWiStErRob** [comment]
Any news here?

**Comment by ZacSweers** [comment]
Opened a PR to fix this here #5432. I'm not sure if Google is actively maintaining the external version of Robolectric anymore though.

**Comment by carstenhag** [comment]
Still occurs on 4.3.1. When is there going to be a new release with this fix? Thanks in advance!

**Comment by jamesonwilliams** [comment]
> Still occurs on 4.3.1. When is there going to be a new release with this fix? Thanks in advance!

4.3.1 was released on Oct 14, 2019, while @ZacSweers's https://github.com/robolectric/robolectric/pull/5432 was merged on Feb 11, 2020. So, it'd be included in some release _after_ 4.3.1.

**Comment by carstenhag** [comment]
Exactly, that's why I was asking when there is going to be a new release.

**Comment by alixwar** [comment]
Why is this issue closed?

**Comment by TWiStErRob** [comment]
Isn't it because it's fixed? (haven't tested)
See the close trigger: https://github.com/robolectric/robolectric/issues/5245#event-3036295659

This line change should fix the issue https://github.com/robolectric/robolectric/pull/5432/files#diff-059aea557df9c39145184e633ffe9ae0R23 and the PR merge commit (https://github.com/robolectric/robolectric/commit/0885c87ba871ce7ee4deea300d8f42b19b8c888d) is is in 4.4.
